openapi: 3.0.0
info:
  title: message-queue
  version: '1.0'
  description: |-
    This document describes the AMQP APIs we design for the RabbitMQ.

    Since Open API Spec is not for AMQP, we can only describe the AMQP elements in the HTTP-like way:

    1. HTTP path => AMQP Topic
    2. The URL 'a.{b}.c' => the topic route 'a.{b}.c' where b is a variable
    3. Response body => payload

    Topic Exchange:

    Every resource root of path is a **Topic Exchange**, for example:
    `submission.{submissiondId}.judge` is a path, then this indicates that
    there is a `submission` Topic exchange.
servers: []
paths:
  'submission.{submissionId}.judge':
    parameters:
      - schema:
          type: integer
        name: submissionId
        in: path
        required: true
    get:
      summary: On submission judge completed
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./judge.v1.yaml
        '':
          content:
            application/json:
              schema:
                $ref: ./judge.v1.yaml
      operationId: get-judges.-submissiondId-.complete
components:
  schemas: {}
