openapi: 3.0.0
info:
  title: problem-service
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/api/problems/{problemId}':
    get:
      summary: Get a problem
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./problem.v1.yaml
      operationId: get-api-problems
      requestBody:
        description: ''
    parameters:
      - schema:
          type: integer
        name: problemId
        in: path
        required: true
        description: ''
  '/api/problems/{problemId}/testcases':
    parameters:
      - type: string
        name: problemId
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Get a list of testcases under a problem
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./testcase.v1.yaml
      operationId: get-api-problems-problemId-testcases
components:
  schemas: {}
