openapi: 3.0.0
info:
  title: student-adapter-service
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/students/login:
    post:
      summary: Login
      operationId: post-api-students
      responses:
        '200':
          description: OK
    parameters: []
components:
  schemas: {}
