openapi: 3.0.0
info:
  title: student-adapter-service
  version: '1.0'
servers:
  - url: 'http://localhost:33001'
paths:
  /api/students/login:
    post:
      summary: Login
      operationId: post-api-students
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
              examples:
                example:
                  value:
                    token: eyJhbGciOiJIUzI1NiJ9.eyJzdHVkZW50SWQiOiJyMTIzNDU2NzgiLCJleHAiOjE1ODU4MDcxNTN9.2_L7au4B40vdcB8P5UNjZ-q8pOhxnULV4vrz_eOzkUg
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                studentId:
                  type: string
                password:
                  type: string
            examples: {}
        description: ''
      parameters: []
    parameters: []
  '/api/students/{studentId}':
    parameters:
      - type: string
        name: studentId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get student info by id
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./student.v1.yaml
      operationId: get-api-students-studentId
      security: []
components:
  schemas: {}
  securitySchemes:
    JWT Token:
      type: http
      scheme: bearer
      description: 'Put the token in the header `Authorization` with the value `Bearer ${token}`. 400 Unauthorized is responded when the token is invalid.'
