openapi: 3.0.0
info:
  title: submission-service
  version: '1.0'
servers:
  - url: 'http://localhost:33003'
paths:
  /api/submissions:
    post:
      summary: Submit Code
      operationId: post-api-submissions
      responses:
        '202':
          description: Accepted
      security:
        - JWT Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                studentId:
                  type: string
                problemId:
                  type: integer
                code:
                  type: string
              required:
                - studentId
                - problemId
                - code
        description: ''
components:
  schemas: {}
  securitySchemes:
    JWT Token:
      type: http
      scheme: bearer
      description: 'Put the token in the header `Authorization` with the value `Bearer ${token}`. 400 Unauthorized is responded when the token is invalid.'
